config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :tweets
  get 'searching', to: 'users#new'
  post 'searching', to: 'users#searching'
  get '/:username', to: 'users#show', as: 'user'
  scope ':username' do
    resources :followings, only: [:index], path: 'following'
    resources :followers, only: [:index]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user, counter_cache: true

  default_scope -> { order(created_at: :DESC) }

  validates :tweet, presence: true, length: { minimum: 1, maximum: 280 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  default_scope -> { order(name: :ASC) }

  has_many :tweets, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  before_save :sanitisize_text

  validates :username, presence: true, uniqueness: true,
                       length: { minimun: 6, maximum: 15 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true,
                    format: { with: VALID_EMAIL_REGEX },
                    length: { maximum: 30 }

  def sanitisize_text
    self.username = username.downcase
    self.name = name.titleize
    self.email = email.downcase
  end

  # follow another user
  def follow(other)
    active_relationships.create(followed_id: other.id)
  end

  # unfollow an user
  def unfollow(other)
    active_relationships.find_by(followed_id: other.id).destroy
  end

  # is following an user?
  def following?(other)
    following.include?(other)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :email])
  end
end

app/controllers/concerns/user_scoped.rb
module UserScoped
  extend ActiveSupport::Concern
  included do
    before_action :set_user
  end

  def set_user
    @user = User.find_by(username: params[:username])
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  include UserScoped

  def index
    @followers_users = @user.followers.paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  include UserScoped

  def index
    @following_users = @user.following.paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user_path(user.username), notice: "Now you are following @#{user.username}"
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user_path(user.username), notice: "You are not following @#{user.username}"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :update, :edit, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if user_signed_in?
      @tweets = Tweet.includes(:user).where(user_id: current_user.following).or(current_user.tweets).paginate(page: params[:page], per_page: 10)
    else
      @tweets = @user.tweets.paginate(page: params[:page], per_page: 10)
    end
    @tweet = Tweet.new
    @users = User.all
    @user = current_user
  end

  def show; end

  def new
    @tweet = current_user.tweets.build
  end

  def edit; end

  def create
    @tweet = current_user.tweets.build(tweet_params)

    if @tweet.save
      flash[:notice] = "Tweet was successfully created."
      redirect_to tweets_path(@tweet)
    else
      render :new
    end
  end

  def update
    if @tweet.update(tweet_params)
      flash[:notice] = "Tweet was successfully updated."
      redirect_to @tweet
    else
      render :edit
    end
  end

  def destroy
    @tweet.destroy
    flash[:notice] = "Tweet was successfully deleted."
    redirect_to tweets_path
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:tweet)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UserScoped

  def new; end

  def show
    @tweets = @user.tweets.paginate(page: params[:page], per_page: 10)
  end

  def searching
    return redirect_to searching_path if params[:followed].blank?

    @follow = User.find_by(username: params[:followed])
    return redirect_to searching_path, alert: 'That user does not exist.' if @follow.blank?

    return redirect_to searching_path, alert: 'Invalid operation.' if current_user == @follow

    if current_user.following.include?(@follow)
      return redirect_to searching_path, alert: "You already follow @#{@follow.username}"
    end

    user_followed = Relationship.create(follower: current_user, followed: @follow)
    redirect_to user_path(@follow.username), notice: "You are now following @#{@follow.username}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/followers/_followers_list.html.erb
<div class="card">
  <div class="card-header">
    <b>Users following <%= @user.name %>:</b>
  </div>
  <% @followers_users.each do |follower| %>
    <ul class="list-group list-group-flush">
      <li class="list-group-item p-0">
        <div class="card-body">
          <p class="card-text">
            <%= gravatar_image_tag(follower.email, :gravatar => { :size => 50 }, class: "rounded-circle mr-1", alt: follower.name) %>
            <br/>
            <b><%= follower.name %></b><br/>
            <small><%= link_to '@' + follower.username, user_path(follower.username), class: "text-decoration-none" %></small>
          </p>
          <% if follower.username != current_user %>
            <% if !current_user.followers.include? follower.username %>
              <%= render partial: 'tweets/follow_button', locals: { user: follower } %>
            <% end %>
          <% end %>
        </div>
      </li>
    </ul>
  <% end %>
</div>

app/views/followers/index.html.erb
<%= render 'followers_list', locals: { followers_users: @followers_users } %>

<div>
  <%= link_to 'Back', root_path, class:"btn btn-primary" %>
</div>

<%= will_paginate @followers_users %>

app/views/followings/_following_list.html.erb
<div class="card">
  <div class="card-header">
    <b>Users followed by <%= @user.name %>: </b>
  </div>
  <% @following_users.each do |followed| %>
    <ul class="list-group list-group-flush">
      <li class="list-group-item p-0">
        <div class="card-body">
          <p class="card-text">
            <%= gravatar_image_tag(followed.email, :gravatar => { :size => 50 }, class: "rounded-circle mr-1", alt: followed.name) %>
            <br/>
            <b><%= followed.name %></b><br/>
            <small><%= link_to '@' + followed.username, user_path(followed.username), class: "text-decoration-none" %></small>
          </p>
          <% if followed.username != current_user %>
            <% if !current_user.following? followed.username %>
              <%= render partial: 'tweets/follow_button', locals: { user: followed } %>
            <% end %>
          <% end %>
        </div>
      </li>
    </ul>
  <% end %>
</div>

app/views/followings/index.html.erb
<%= render 'following_list', locals: { following_users: @following_users } %>

<div>
  <%= link_to 'Back', root_path, class:"btn btn-primary" %>
</div>

<div>
  <%= link_to 'Follow Another user', searching_path %>
</div>

<%= will_paginate @following_users %>

app/views/home/_dashboard.html.erb
<h1>Welcome to your dashboard!</h1>

app/views/home/_welcome.html.erb
<div class="row h-100">
  <div class="col-8" id="columns">
    <%= image_tag 'twitter_logo.png', class: 'cover-background' %>
  </div>
  <div class="col-4" id="columns">
    <div class="col">
      <i class="fab fa-twitter little-bird"></i>
      <div class="text1">
        <span>Happening now</span>
      </div><br>
      <div class="text2">
        <span>Join Twitter today.</span>
      </div><br>
      <div class="d-grid gap-2 col-6">
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary rounded-pill' %>
        <%= link_to "Log In", new_user_session_path, class: 'btn btn-outline-primary rounded-pill' %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <% controller.redirect_to tweets_path %>
<% else %>
  <%= render 'welcome' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/2459a8b6de.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render partial: 'shared/header' %>
    <% end %>

    <%= render partial: 'shared/flash' %>
    <%= yield %>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Twitter</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Tweet", new_tweet_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Hi @' + current_user.username + '!', user_path(current_user.username), class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-outline-light rounded-pill" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tweets/_feed.html.erb
<br/>

<div class="container">
  <div class="row align-items-start">
    <div class="col-5">
      <%= render partial: 'tweets/profile', locals: { user: @user} %>
    </div>
    <div class="col-7">
      <% @tweets.each do |tweet| %>
        <div class="card">
          <div class="card-body">
            <%= gravatar_image_tag(current_user.email, :gravatar => { :size => 50 }, class: "rounded-circle mr-1", alt: current_user.name) %>
            <p><strong><%= tweet.user.name %></strong>,
            <%= '@' + tweet.user.username %><%= ' · ' + tweet.created_at.getlocal.strftime("%d %b. %Y · %I:%M %P") %></p>
            <p><%= tweet.tweet %></p>

            <% if user_signed_in? && current_user.id == tweet.user_id %>
              <nav class="level">
                <div class="level-left is-mobile">
                  <%= link_to tweet, class: "level-item" do %>
                    <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                  <% end %>
                  <%= link_to tweet, method: :delete, data: { confirm: "Are you sure you want to delete this tweeet?" } do %>
                    <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                  <% end %>
                </div>
              </nav>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/_follow_button.html.erb
<div>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
      html: { method: :delete }) do |f| %>
      <%= f.submit "Unfollow", class: "btn btn-primary btn-sm rounded-pill" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.active_relationships.build) do |f| %>
      <div>
        <%= hidden_field_tag :followed_id, user.id %>
      </div>
      <%= f.submit "Follow", class: "btn btn-primary btn-sm rounded-pill" %>
    <% end %>
  <% end %>
</div>

app/views/tweets/_form.html.erb
<div class="card">
  <div class="card-body">
    <%= form_with model: @tweet do |f| %>
      <% if @tweet.errors.any? %>
        <div class="alert alert-danger">
          <% @tweet.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </div>
      <% end %>
      <div class="mb-3">
        <%= f.text_area :tweet, class: 'form-control', placeholder: 'What is happening?' %>
      </div>
      <div class="mb-3">
        <%= f.submit 'Tweet', class: 'btn btn-primary rounded-pill mx-auto' %>
      </div>
    <% end %>
  </div>
</div>

app/views/tweets/_profile.html.erb
<div class="card">
  <img src="https://picsum.photos/600/200" class="card-img-top" alt="Lorem picsum random image" %>
  <div class="card-body">
    <h5 class="card-title">
      <%= gravatar_image_tag(@user.email, size: 64, class: "rounded-circle mr-1",alt: @user.name) %>
    </h5>
    <% if user_signed_in? %>
      <p class="card-text">
        <strong><%= @user.name %></strong><br/>
        <small>@<%= @user.username %></small>
      </p>
      <% if (current_user != @user) %>
        <%= render 'tweets/follow_button', user: @user %>
      <% end %>
    <% else %>
      <p class="card-text">
        <strong><%= @user.name %></strong><br/>
        <small><%= '@' + @user.username %></small>
      </p>
      <%= render 'tweets/follow_button', :user => User.find_by_username(params[:id]) %>
    <% end %>
    <div class="container border-top px-0">
      <div class="row justify-content-center">
        <div class="col text-center mt-3 px-2">
          <p>
            <small><b><%= @user.tweets.size %></b></small>
            <small>Tweets</small>
          </p>
        </div>
        <div class="col mt-3 text-center px-2">
          <p>
            <small><b><%= @user.following.count %></b></small>
            <small><%= link_to 'Following', followings_path(@user.username), class: "text-decoration-none" %></small>
          </p>
        </div>
        <div class="col mt-3 text-center px-2">
          <p>
            <small><b><%= @user.followers.count %></b></small>
            <small><%= link_to 'Followers', followers_path(@user.username), class: "text-decoration-none" %></small>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tweets/_who_to_follow.html.erb
<div class="card">
  <div class="card-header">
    <b>Who to follow</b>
  </div>
  <% @users.each do |user| %>
    <% if current_user.id != user.id %>
      <ul class="list-group list-group-flush">
        <li class="list-group-item p-0">
          <div class="card-body">
            <%= gravatar_image_tag(user.email, :gravatar => { :size => 50 }, class: "rounded-circle mr-1", alt: user.name) %>
            <p class="card-text">
              <b><%= user.name %></b><br/>
              <small><%= '@'+user.username %></small>
            </p>
            <%= render 'follow_button', user: user %>
          </div>
        </li>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/tweets/index.html.erb
<br/>

<%= render partial: 'feed', locals: { user: @user } %>
<br/>
<%= will_paginate @tweets %>
<br/>

app/views/tweets/new.html.erb
<br/>

<%= render 'form'%>

app/views/tweets/show.html.erb
<div class="card">
  <div class="card-body">
    <%= gravatar_image_tag(current_user.email, :gravatar => { :size => 50 }, class: "rounded-circle mr-1", alt: current_user.name) %>
    <p><strong><%= @tweet.user.name %></strong>,
    <%= '@' + @tweet.user.username + '·' + @tweet.created_at.getlocal.strftime("%d %b. %Y · %I:%M %P") %></p>
    <p><%= @tweet.tweet %></p>

    <% if user_signed_in? && current_user.id == @tweet.user_id %>
      <nav class="level">
        <div class="level-left is-mobile">
          <%= link_to 'Back', tweets_path, class: "btn btn-primary btn-sm" %>
          <%= link_to tweet_path, method: :delete, data: { confirm: "Are you sure you want to delete this tweet?" } do %>
            <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
          <% end %>
        </div>
      </nav>
    <% end %>
  </div>
</div>

app/views/users/_user_tweets.html.erb
<% if @user.tweets.any? %>
  <div class="col-7">
    <% @tweets.each do |tweet| %>
      <div class="card">
        <div class="card-body">
          <%= gravatar_image_tag(current_user.email, :gravatar => { :size => 50 }, class: "rounded-circle mr-1", alt: current_user.name) %>
          <p><strong><%= tweet.user.name %></strong>,
          <%= '@' + tweet.user.username + ' · ' + tweet.created_at.getlocal.strftime("%d %b. %Y · %I:%M %P") %></p>
          <p><%= tweet.tweet %></p>

          <% if user_signed_in? && current_user.id == tweet.user_id %>
            <nav class="level">
              <div class="level-left is-mobile">
                <%= link_to tweet, class: "level-item" do %>
                  <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                <% end %>
                <%= link_to tweet, method: :delete, data: { confirm: "Are you sure you want to delete this tweeet?" } do %>
                  <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                <% end %>
              </div>
            </nav>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="col-7">
    <div class="card">
      <div class="card-body">
        <%= 'Ups, @' + @user.username + ' has no tweets yet. ' %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<% if user_signed_in? %>
  <h3 class="text-center">Follow another user</h3>

  <%= form_with(url: searching_path, local:true) do |f| %>
    <div class="form-group">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1">@</span>
        </div>
        <%= f.text_field :followed, class: "form-control", placeholder: "username" %>
      </div>
    </div>
    <%= f.submit "Follow user", class: "btn btn-primary" %>
  <%end%>
<% end %>

app/views/users/searching.html.erb
<% if user_signed_in? %>
  <h3 class="text-center">Follow another user</h3>

  <%= form_with(url: searching_path, local:true) do |f| %>
    <div class="form-group">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1">@</span>
        </div>
        <%= f.text_field :followed, class: "form-control", placeholder: "username" %>
      </div>
    </div>
    <%= f.submit "Follow user", class: "btn btn-primary" %>
  <%end%>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="col-7">
  <%= render partial: 'tweets/profile', locals: {user: @user} %>
</div>

<%= render 'user_tweets', locals: {tweets: @tweets} %>

<%= will_paginate @tweets %>